flow:
  training: true
  testing: false

dataset:
  data_features_dir: "features/feature_extractor_6ae3fd977a9a7419a085de1a0209ce46"
  data_eval_features_dir: "eval_features/feature_extractor_6ae3fd977a9a7419a085de1a0209ce46"
  data_parent_dir: "/home/trann/scratch/advanced-audio/data/"
  meta_parent_dir: "/home/trann/scratch/TAU-urban-acoustic-scenes-2020-mobile/TAU-urban-acoustic-scenes-2020-mobile-development/evaluation_setup" 
  meta_train_dir: "fold1_train.csv"
  meta_val_dir: "fold1_evaluate.csv"
  meta_eva_dir: "fold1_validation.csv"

model:
  model_name: "resnest"
  submodel_name: "resnest50_fast_1s2x40d"
  pretrained: true
  n_classes: 10

hyperparams:
  batch_size: 16 
  epochs: 100
  num_workers: 4
  patience: 20
  loss_thr: !!float 1e-4
  optimizer:
    lr: !!float 1e-3
  grad_norm:
    value: !!float 1.
    norm: 2
  save_model: "resnest50_fast_1s2x40d_2.pt"